import { createFileRoute } from "@tanstack/react-router";
import { ArrowUpDown, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { Panel, PageHeader } from "@/components/Panel";
import { PrototypeBanner } from "@/components/PrototypeBanner";
import { SensorChart } from "@/components/SensorChart";
import { StatusBadge } from "@/components/StatusBadge";
import { DELTA_THRESHOLD } from "@/data/mockData";
import { useHistoricalData } from "@/hooks/useSensorData";
import type { SensorReading } from "@/types/sensor";
import { formatDateTime } from "@/utils/format";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/historical-data")({
  head: () => ({
    meta: [
      { title: "Historical Data — AIoT Aquaculture" },
      {
        name: "description",
        content:
          "Browse, filter and sort 24 hours of aquaculture sensor history: temperature, TDS, predicted DO, biological delta and status.",
      },
      { property: "og:title", content: "Historical Data — AIoT Aquaculture" },
      {
        property: "og:description",
        content: "24 hours of ESP32 sensor history with charts and a searchable table.",
      },
    ],
  }),
  component: HistoricalPage,
});

type SortKey = keyof Pick<
  SensorReading,
  "timestamp" | "temperature" | "tds" | "predictedDO" | "delta"
>;

const SENSOR_OPTIONS = [
  { id: "all", label: "All parameters" },
  { id: "temperature", label: "Temperature" },
  { id: "tds", label: "TDS" },
  { id: "predictedDO", label: "Predicted DO" },
  { id: "delta", label: "Biological Delta" },
] as const;

const PAGE_SIZE = 10;

function HistoricalPage() {
  const [hours, setHours] = useState(24);
  const { data } = useHistoricalData(hours);
  const [sensor, setSensor] = useState<(typeof SENSOR_OPTIONS)[number]["id"]>("all");
  const [query, setQuery] = useState("");
  const [sortKey, setSortKey] = useState<SortKey>("timestamp");
  const [asc, setAsc] = useState(false);
  const [page, setPage] = useState(1);

  const rows = useMemo(() => {
    const q = query.trim().toLowerCase();
    const filtered = data.filter((r) =>
      q
        ? formatDateTime(r.timestamp).toLowerCase().includes(q) ||
          r.status.toLowerCase().includes(q) ||
          String(r.temperature).includes(q) ||
          String(r.tds).includes(q)
        : true,
    );
    return [...filtered].sort((a, b) => {
      const av = sortKey === "timestamp" ? new Date(a.timestamp).getTime() : a[sortKey];
      const bv = sortKey === "timestamp" ? new Date(b.timestamp).getTime() : b[sortKey];
      return asc ? Number(av) - Number(bv) : Number(bv) - Number(av);
    });
  }, [data, query, sortKey, asc]);

  const pageCount = Math.max(1, Math.ceil(rows.length / PAGE_SIZE));
  const current = Math.min(page, pageCount);
  const visible = rows.slice((current - 1) * PAGE_SIZE, current * PAGE_SIZE);

  const toggleSort = (key: SortKey) => {
    if (key === sortKey) setAsc((a) => !a);
    else {
      setSortKey(key);
      setAsc(false);
    }
  };

  const show = (id: string) => sensor === "all" || sensor === id;

  return (
    <div className="space-y-6">
      <PageHeader
        title="Historical Data"
        subtitle="Recorded sensor readings and edge AI predictions"
      />
      <PrototypeBanner note="History is generated by the mock data service. Once the API is connected, the same table and charts will render real records." />

      <Panel title="Filters" description="Time window, parameter selector and search">
        <div className="grid gap-3 md:grid-cols-3">
          <label className="block">
            <span className="mb-1.5 block text-xs uppercase tracking-wider text-muted-foreground">
              Time range
            </span>
            <select
              value={hours}
              onChange={(e) => {
                setHours(Number(e.target.value));
                setPage(1);
              }}
              className="w-full rounded-lg border border-input bg-secondary/50 px-3 py-2 text-sm outline-none focus:border-ring"
            >
              <option value={6}>Last 6 hours</option>
              <option value={12}>Last 12 hours</option>
              <option value={24}>Last 24 hours</option>
            </select>
          </label>
          <label className="block">
            <span className="mb-1.5 block text-xs uppercase tracking-wider text-muted-foreground">
              Sensor / parameter
            </span>
            <select
              value={sensor}
              onChange={(e) => setSensor(e.target.value as typeof sensor)}
              className="w-full rounded-lg border border-input bg-secondary/50 px-3 py-2 text-sm outline-none focus:border-ring"
            >
              {SENSOR_OPTIONS.map((o) => (
                <option key={o.id} value={o.id}>
                  {o.label}
                </option>
              ))}
            </select>
          </label>
          <label className="block">
            <span className="mb-1.5 block text-xs uppercase tracking-wider text-muted-foreground">
              Search
            </span>
            <span className="relative block">
              <Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
              <input
                value={query}
                onChange={(e) => {
                  setQuery(e.target.value);
                  setPage(1);
                }}
                placeholder="Search timestamp, value or status"
                className="w-full rounded-lg border border-input bg-secondary/50 py-2 pl-9 pr-3 text-sm outline-none focus:border-ring"
              />
            </span>
          </label>
        </div>
      </Panel>

      <div className="grid gap-6 xl:grid-cols-2">
        {show("temperature") && (
          <Panel title="Temperature History">
            <SensorChart
              data={data}
              series={[
                { key: "temperature", name: "Temperature", color: "var(--color-chart-1)", unit: "°C" },
              ]}
            />
          </Panel>
        )}
        {show("tds") && (
          <Panel title="TDS History">
            <SensorChart
              data={data}
              series={[{ key: "tds", name: "TDS", color: "var(--color-chart-2)", unit: "ppm" }]}
            />
          </Panel>
        )}
        {show("predictedDO") && (
          <Panel title="Predicted DO History">
            <SensorChart
              data={data}
              series={[
                { key: "predictedDO", name: "Predicted DO", color: "var(--color-chart-3)", unit: "mg/L" },
              ]}
            />
          </Panel>
        )}
        {show("delta") && (
          <Panel title="Biological Delta History">
            <SensorChart
              data={data}
              threshold={DELTA_THRESHOLD}
              series={[
                { key: "delta", name: "Biological Delta", color: "var(--color-chart-4)", unit: "mg/L" },
              ]}
            />
          </Panel>
        )}
      </div>

      <Panel
        title="Readings"
        description={`${rows.length} records`}
        bodyClassName="p-0"
      >
        <div className="overflow-x-auto">
          <table className="w-full min-w-[720px] text-sm">
            <thead>
              <tr className="border-b border-border text-left text-xs uppercase tracking-wider text-muted-foreground">
                {(
                  [
                    ["timestamp", "Timestamp"],
                    ["temperature", "Temperature"],
                    ["tds", "TDS"],
                    ["predictedDO", "Predicted DO"],
                    ["delta", "Delta"],
                  ] as [SortKey, string][]
                ).map(([key, label]) => (
                  <th key={key} className="px-5 py-3 font-medium">
                    <button
                      onClick={() => toggleSort(key)}
                      className={cn(
                        "inline-flex items-center gap-1.5 hover:text-foreground",
                        sortKey === key && "text-primary",
                      )}
                    >
                      {label}
                      <ArrowUpDown className="size-3" />
                    </button>
                  </th>
                ))}
                <th className="px-5 py-3 font-medium">Status</th>
              </tr>
            </thead>
            <tbody>
              {visible.map((r) => (
                <tr key={r.timestamp} className="border-b border-border/60 last:border-0">
                  <td className="px-5 py-3 font-mono text-xs text-muted-foreground">
                    {formatDateTime(r.timestamp)}
                  </td>
                  <td className="px-5 py-3 font-mono">{r.temperature.toFixed(1)} °C</td>
                  <td className="px-5 py-3 font-mono">{r.tds} ppm</td>
                  <td className="px-5 py-3 font-mono">{r.predictedDO.toFixed(2)} mg/L</td>
                  <td className="px-5 py-3 font-mono">{r.delta.toFixed(2)} mg/L</td>
                  <td className="px-5 py-3">
                    <StatusBadge label={r.status} />
                  </td>
                </tr>
              ))}
              {!visible.length && (
                <tr>
                  <td colSpan={6} className="px-5 py-10 text-center text-muted-foreground">
                    No readings match the current filters.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
        <div className="flex items-center justify-between gap-3 border-t border-border px-5 py-3 text-xs text-muted-foreground">
          <span>
            Page {current} of {pageCount}
          </span>
          <div className="flex gap-2">
            <button
              onClick={() => setPage((p) => Math.max(1, p - 1))}
              disabled={current === 1}
              className="rounded-md border border-border px-3 py-1.5 hover:bg-secondary disabled:opacity-40"
            >
              Previous
            </button>
            <button
              onClick={() => setPage((p) => Math.min(pageCount, p + 1))}
              disabled={current === pageCount}
              className="rounded-md border border-border px-3 py-1.5 hover:bg-secondary disabled:opacity-40"
            >
              Next
            </button>
          </div>
        </div>
      </Panel>
    </div>
  );
}
